# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dd27010090b272dcb5124414e86f895179b97eead880364609096b49fab2968c344b1b5ac67a99e4eff253cba9f5cd9e2d030da0953bdccf0741badcdebdec9

test:
  secret_key_base: 9730e79911077ec0a021d2851c46dcb729aa9a8421fec601de2098a62a6b687dfec110e5818d845bbb7e1b372bebcc5fad4f37eee2454391d70bc9a644b11d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
